name: 龙奇课题组  long Research Group
url: https://lq7799.github.io/

interests: music

# Navigation bar links.
navigation:
  - title: 主页 Home
    link: /
  - title: 科研项目 Research
    link: /research.html
  - title: 论文 Publications
    link: /publications.html
